version: "3.8"

services:
    server:
        build: .
        container_name: express_server
        restart: unless-stopped
        ports:
            - "3001:3001"
        env_file:
            - .env
        networks:
            - app_net
        command:
            - /app/wait-for-it.sh
            - rabbitmq
            - "5672"
            - /app/wait-for-it.sh
            - musescore.crgga8cgyw0v.eu-central-1.rds.amazonaws.com
            - "5432"
            - node
            - /app/server/index.js
    consumer:
        build: .
        container_name: consumer_worker
        restart: unless-stopped
        env_file:
            - .env
        depends_on:
            - rabbitmq
        networks:
            - app_net
        command:
            - /app/wait-for-it.sh
            - rabbitmq
            - "5672"
            - /app/wait-for-it.sh
            - musescore.crgga8cgyw0v.eu-central-1.rds.amazonaws.com
            - "5432"
            - node
            - /app/consumer/consumer.js
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - app_net

networks:
    app_net:
        driver: bridge
