version: "3.8"

services:
    server:
        build: .
        container_name: express_server
        restart: unless-stopped
        ports:
            - "3001:3001"
        environment:
            - PORT=3001
            - QUEUE=score_links
            - RABBITMQ_URL=amqp://rabbitmq
            - rabbitmq
            - DATABASE_URL=postgresql://postgres:ZMM5n72yUAdreTC3v9jZ@musescore.crgga8cgyw0v.eu-central-1.rds.amazonaws.com:5432/musescore?schema=public
        networks:
            - app_net
        command:
            - /app/wait-for-it.sh
            - rabbitmq
            - "5672"
            - /app/wait-for-it.sh
            - musescore.crgga8cgyw0v.eu-central-1.rds.amazonaws.com
            - "5432"
            - node
            - /app/server/index.js
    consumer:
        build: .
        container_name: consumer_worker
        restart: unless-stopped
        environment:
            - QUEUE=score_links
            - RABBITMQ_URL=amqp://rabbitmq
            - DATABASE_URL=postgresql://postgres:ZMM5n72yUAdreTC3v9jZ@musescore.crgga8cgyw0v.eu-central-1.rds.amazonaws.com:5432/musescore?schema=public
        depends_on:
            - rabbitmq
        networks:
            - app_net
        command:
            - /app/wait-for-it.sh
            - rabbitmq
            - "5672"
            - /app/wait-for-it.sh
            - musescore.crgga8cgyw0v.eu-central-1.rds.amazonaws.com
            - "5432"
            - node
            - /app/consumer/consumer.js
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - app_net

networks:
    app_net:
        driver: bridge
